version: '3.8'

services:
  # --- Text-to-Speech Service: Kokoro (Intel iGPU via OpenVINO) ---
  kokoro-tts:
    build: ./kokoro-tts
    container_name: orator-kokoro
    restart: unless-stopped
    ports:
      - "8880:8880"
    environment:
      DEVICE: "${KOKORO_DEVICE:-CPU}"  # CPU, IGPU, or CUDA
      DEFAULT_VOICE: "${KOKORO_VOICE:-af}"
    devices:
      - /dev/dri:/dev/dri  # For Intel iGPU support
    group_add:
      - "44"    # video group
      - "993"   # render group (may vary by system)
    volumes:
      - kokoro_models:/app/models
    networks:
      orator-network:
        aliases:
          - kokoro
          - tts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8880/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # --- Nginx Reverse Proxy (optional) ---
  nginx:
    image: nginx:alpine
    container_name: orator-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - orator-network
    depends_on:
      - kokoro-tts

networks:
  orator-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  kokoro_models: